apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres
    template:
        metadata:
            labels:
                component: postgres
        spec:
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim: # go to this claim object and use the requirements defined there
                    claimName: database-persistent-volume-claim
            containers:
                - name: postgres
                  image: postgres
                  ports:
                    - containerPort: 5432
                  volumeMounts: # how to use the storage
                    - name: postgres-storage
                      mountPath: /var/lib/postgresql/data
                      subPath: postgres # store any data in a sub folder called postgres in this storage volume, is postgres specific
                  env:
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: pgpassword
                          key: PGPASSWORD