apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes:
        - ReadWriteOnce # can be used by a single node at a time
    resources:
        requests:
            storage: 1Gi # has to have 2 GB worth of space